language: ruby

addons:
  postgresql: 9.4

rvm:
  - 2.2.2
  - 2.2.3

services:
  - redis

sudo: false

cache: bundler

before_script:
  - cp config/database.yml.ci config/database.yml
  - cp config/exsules.yml.example config/exsules.yml
  - 'RAILS_ENV=test bundle exec rake db:create db:migrate --trace'

bundler_args: --without development --jobs 3 --retry 3

script:
  - 'RAILS_ENV=test SIMPLECOV=true bundle exec rspec'